# Generated by Django 3.2.5 on 2022-10-24 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resources',
            new_name='Resource',
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, help_text='When will the user start taking this course', null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='course',
            field=models.ForeignKey(blank=True, help_text='            If this timetable is for a specific course, fill out this field', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.course'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='            If this timetable if for a specific topic, fill out this fiedld', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.topic'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, help_text='What is this list for.', null=True),
        ),
    ]
