# Generated by Django 3.2.5 on 2022-10-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20221024_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
