# Generated by Django 3.2.5 on 2022-10-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20221024_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='progress',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
