# Generated by Django 3.2.5 on 2022-10-26 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_course_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='tracker.section'),
        ),
    ]
