# Generated by Django 3.2.5 on 2022-10-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_course_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.URLField(blank=True, help_text='Url to an online resource, video, document e.t.c', null=True),
        ),
    ]
