# Generated by Django 3.2.5 on 2022-10-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_alter_resource_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='video',
            field=models.FileField(blank=True, help_text='Video resource for a course', null=True, upload_to=''),
        ),
    ]
