# Generated by Django 3.2.5 on 2022-10-28 07:23

from django.db import migrations, models
import tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_resource_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='pdf',
        ),
        migrations.AddField(
            model_name='resource',
            name='document',
            field=models.FileField(blank=True, help_text='Document resource for a course', null=True, upload_to='uploads/documents', validators=[tracker.validators.document_file_validator]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='audio',
            field=models.FileField(blank=True, help_text='Audio resource like a lecture recording', null=True, upload_to='uploads/audio', validators=[tracker.validators.audio_file_validator]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='video',
            field=models.FileField(blank=True, help_text='Video resource for a course', null=True, upload_to='uploads/video', validators=[tracker.validators.video_file_validator]),
        ),
    ]
