# Generated by Django 3.2.5 on 2022-10-28 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20221028_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableactivity',
            name='timetable',
            field=models.ForeignKey(help_text='What time table does this activity belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='table_items', to='tracker.timetable'),
        ),
    ]
