# Generated by Django 3.2.5 on 2022-10-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_timetableactivity_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableactivity',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Su'), ('Monday', 'Mo'), ('Tuesday', 'Tu'), ('Wednesday', 'We'), ('Thursday', 'Th'), ('Friday', 'Fr'), ('Saturday', 'Sa')], help_text='Day for this activity', max_length=10),
        ),
    ]
