# Generated by Django 3.2.5 on 2022-10-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_alter_timetableactivity_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableactivity',
            name='day',
            field=models.CharField(choices=[('SU', 'Sunday'), ('MO', 'Monday'), ('TU', 'Tuesday'), ('WE', 'Wednesday'), ('TH', 'Thursday'), ('FR', 'Friday'), ('SA', 'Saturday')], help_text='Day for this activity', max_length=2),
        ),
    ]
