# Generated by Django 3.2.5 on 2022-10-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_alter_timetableactivity_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableactivity',
            name='day',
            field=models.CharField(choices=[('SUNDAY', 'Sunday'), ('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday')], help_text='Day for this activity', max_length=10),
        ),
    ]
