# Generated by Django 3.2.5 on 2022-10-28 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_alter_timetableactivity_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='todo_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracker.todo'),
            preserve_default=False,
        ),
    ]
