# Generated by Django 3.2.5 on 2022-11-15 16:26

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_auto_20221105_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='document',
            field=models.FileField(blank=True, help_text='Document resource for a course', null=True, upload_to='uploads/documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(blank=True, help_text='Image resource for a course.', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='uploads/images'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='video',
            field=models.FileField(blank=True, help_text='Video resource for a course', null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage, upload_to='uploads/video'),
        ),
    ]
